### ISSUE TITLE
When run with nomad_server set, script in /etc/init/nomad.conf is blank

### ISSUE THREAD

**Issue by msabramo** [kbrebanov/ansible-nomad#5]
I used this playbook:

``` yaml
- hosts: nomad_servers
  vars:
    use_nomad: true
    nomad_server: true
    nomad_server_bootstrap_expect: "{{ play_hosts|length }}"
  roles:
    - role: kbrebanov.nomad
      tags: nomad
      when: use_nomad
      sudo: yes
```

and the result was:

```
ENDOR\marca@sjc-cmdb01:~$ cat /etc/init/nomad.conf
description "Service for nomad"
author "Kevin Brebanov"

start on filesystem or runlevel [2345]
stop on shutdown

reload signal SIGHUP

respawn
respawn limit 10 10
kill timeout 10

script
end script

post-stop script
    rm -f /var/run/nomad.pid
end script
```

Note how the script for launching nomad is blank.
